### ISSUE TITLE
Instruction Decoder

### ISSUE THREAD

**Issue by foez-ahmed** [Chip-DSi/simple_processor_BUET#21]
The IOs of the instruction decoder should be something like this:
``` SV
module instruction_decoder (
  input  logic [15:0] code_i,
  output func_t       func_o,
  output logic         we_o,
  output logic [2:0]  rd_addr_o,
  output logic [2:0]  rs1_addr_o,
  output logic [2:0]  rs2_addr_o,
  output logic [31:0] imm_o
);
```

**Comment by anindyakchoudhury** [comment]
Is immediate a 32-bit value coming out of ID? or is it a 6-bit value? Because IMEM stores 16 bit of instructions_width. IMM is not stored in any kind of memory either and comes from the user input.

![image](https://github.com/Chip-DSi/simple_processor_BUET/assets/69748292/f3089375-3483-47c6-8c24-f41564d3939d)

**Comment by foez-ahmed** [comment]
Yes, please convert it to a 32bit signed number before sending it to muxing with rs2

**Comment by anindyakchoudhury** [comment]
Bhaiya, when instr_t is used? @foez-ahmed

**Comment by foez-ahmed** [comment]
`instr_t` is not `func_t`
